- name: tailscale | setup_repository
  ansible.builtin.yum_repository:
    name: tailscale
    description: Tailscale stable
    baseurl: https://pkgs.tailscale.com/stable/centos/9/$basearch
    gpgkey: https://pkgs.tailscale.com/stable/centos/9/repo.gpg
    enabled: true
    gpgcheck: false
    repo_gpgcheck: true
- name: tailscale | install
  become: true
  ansible.builtin.dnf:
    name: tailscale
- name: tailscale | auto-start
  ansible.builtin.service:
    name: tailscaled
    state: started
    enabled: true
